Repository sei-protocol/sei-chain, pull requests merged in 2023-05, with the labels that each got.

#753 2.0.48beta release
  CHANGELOG.md
  app/upgrades.go
  go.mod
  go.sum
Labels: release

#231 Update readme.md
  readme.md
Labels: documentation

#107 codeql from cosmos-sdk by way of crypto.com.
  .github/workflows/codeql.yml
Labels: enhancement

#335 Fix readme.md
  readme.md
Labels: documentation

#330 Fix: typo
  readme.md
Labels: documentation

#746 Clear unregistered contracts from other contracts dependency list
  proto/dex/contract.proto
  utils/datastructures/set.go
  x/dex/keeper/contract.go
  x/dex/keeper/contract_test.go
  x/dex/module.go
Labels: enhancement
