Repository sei-protocol/sei-chain, pull requests merged in 2024-03, with the labels that each got.

#1398 Merge in the OCC changes in seiv2 into main
  .github/workflows/codeql.yml
  .github/workflows/compatiblity_check.yml
  .github/workflows/fuzz.yml
  .github/workflows/golangci.yml
  .github/workflows/integration-test.yml
  .github/workflows/proto-registry.yml
  .github/workflows/unit_tests.yml
  aclmapping/dex/mappings.go
  aclmapping/utils/resource_type.go
  aclmapping/utils/resource_type_test.go
  app/abci.go
  app/app.go
  app/app_test.go
  app/test_helpers.go
  cmd/seid/cmd/root.go
  go.mod
  go.sum
  loadtest/config.json
  loadtest/contracts/deploy_erc20.sh
  loadtest/contracts/evm/.gitignore
  loadtest/contracts/evm/bindings/erc20/abi.json
  loadtest/contracts/evm/bindings/erc20/erc20.go
  loadtest/contracts/evm/foundry.toml
  loadtest/contracts/evm/remappings.txt
  loadtest/contracts/evm/setup.sh
  loadtest/contracts/evm/src/NoopToken.sol
  loadtest/evm.go
  loadtest/loadtest_client.go
  loadtest/main.go
  loadtest/scripts/generate_bindings.sh
  loadtest/sign.go
  loadtest/tx.go
  loadtest/types.go
  occ_tests/messages/test_msgs.go
  occ_tests/occ_test.go
  occ_tests/utils/utils.go
  proto/dex/contract.proto
  scripts/initialize_local_chain.sh
  utils/metrics/metrics_util.go
  x/dex/cache/cache.go
  x/dex/contract/abci.go
  x/dex/keeper/msgserver/msg_server_register_contract.go
  x/dex/keeper/msgserver/msg_server_unregister_contract.go
  x/dex/keeper/msgserver/msg_server_unsuspend_contract.go
  x/dex/module.go
  x/dex/types/contract.pb.go
  x/dex/types/keys.go
  x/oracle/types/test_utils.go
Labels: non-app-hash-breaking

#1403 Revert "Merge in the OCC changes in seiv2 into main"
  .github/workflows/codeql.yml
  .github/workflows/compatiblity_check.yml
  .github/workflows/fuzz.yml
  .github/workflows/golangci.yml
  .github/workflows/integration-test.yml
  .github/workflows/proto-registry.yml
  .github/workflows/unit_tests.yml
  aclmapping/dex/mappings.go
  aclmapping/utils/resource_type.go
  aclmapping/utils/resource_type_test.go
  app/abci.go
  app/app.go
  app/app_test.go
  app/test_helpers.go
  cmd/seid/cmd/root.go
  go.mod
  go.sum
  loadtest/config.json
  loadtest/contracts/deploy_erc20.sh
  loadtest/contracts/evm/.gitignore
  loadtest/contracts/evm/bindings/erc20/abi.json
  loadtest/contracts/evm/bindings/erc20/erc20.go
  loadtest/contracts/evm/foundry.toml
  loadtest/contracts/evm/remappings.txt
  loadtest/contracts/evm/setup.sh
  loadtest/contracts/evm/src/NoopToken.sol
  loadtest/evm.go
  loadtest/loadtest_client.go
  loadtest/main.go
  loadtest/scripts/generate_bindings.sh
  loadtest/sign.go
  loadtest/tx.go
  loadtest/types.go
  occ_tests/messages/test_msgs.go
  occ_tests/occ_test.go
  occ_tests/utils/utils.go
  proto/dex/contract.proto
  scripts/initialize_local_chain.sh
  utils/metrics/metrics_util.go
  x/dex/cache/cache.go
  x/dex/contract/abci.go
  x/dex/keeper/msgserver/msg_server_register_contract.go
  x/dex/keeper/msgserver/msg_server_unregister_contract.go
  x/dex/keeper/msgserver/msg_server_unsuspend_contract.go
  x/dex/module.go
  x/dex/types/contract.pb.go
  x/dex/types/keys.go
  x/oracle/types/test_utils.go
Labels: non-app-hash-breaking

#1406 Bump seidb version to latest
  go.mod
  go.sum
Labels: non-app-hash-breaking

#1407 Bump seidb version to latest
  go.mod
  go.sum
Labels: non-app-hash-breaking

#1405 [EVM] fix empty tx root value
  evmrpc/block.go
  evmrpc/block_test.go
Labels: non-app-hash-breaking

#1417 [EVM] set default block to latest for eth_getLogs
  evmrpc/block_test.go
  evmrpc/filter.go
  evmrpc/filter_test.go
  evmrpc/setup_test.go
  evmrpc/subscribe_test.go
Labels: non-app-hash-breaking

#1411 Integrate with tendermint EVM tx replacement logic
  app/app.go
  go.mod
  go.sum
  x/evm/ante/sig.go
  x/evm/ante/sig_test.go
  x/evm/client/cli/tx.go
  x/evm/keeper/keeper.go
  x/evm/keeper/keeper_test.go
Labels: non-app-hash-breaking

#1418 bump sei-wasmd
  go.mod
  go.sum
  wasmbinding/encoder.go
Labels: app-hash-breaking

#1425 Set address association for Cosmos tx
  app/ante.go
  precompiles/wasmd/wasmd_test.go
  x/evm/ante/preprocess.go
  x/evm/ante/preprocess_test.go
  x/evm/ante/router_test.go
Labels: app-hash-breaking

#1424 Remove command output that breaks loadtest deploying
  loadtest/contracts/deploy_erc20.sh
Labels: non-app-hash-breaking

#1428 [EVM] Add erc721 to loadtest
  contracts/src/ERC721.sol
  contracts/test/ERC721Test.js
  loadtest/contracts/deploy_erc721.sh
  loadtest/contracts/evm/bindings/erc721/abi.json
  loadtest/contracts/evm/bindings/erc721/erc721.go
  loadtest/contracts/evm/src/ERC721.sol
  loadtest/evm.go
  loadtest/loadtest_client.go
  loadtest/main.go
  loadtest/types.go
Labels: non-app-hash-breaking

#1429 Add funding logic to erc721 deploy script
  .github/workflows/compatiblity_check.yml
  loadtest/contracts/deploy_erc20.sh
  loadtest/contracts/deploy_erc721.sh
Labels: non-app-hash-breaking

#1432 Pass `.git` folder to Docker context
  .dockerignore
Labels: non-app-hash-breaking

#1427 Add deny list config for EVM RPC
  evmrpc/config.go
  evmrpc/config_test.go
  evmrpc/rpcstack.go
  evmrpc/rpcstack_test.go
  go.mod
  go.sum
Labels: non-app-hash-breaking

#1422 v3.8.0-release seiv2
  CHANGELOG.md
  app/upgrades.go
  go.mod
  go.sum
Labels: non-app-hash-breaking

#1434 V4.1.5 evm devnet release
  app/upgrades.go
Labels: non-app-hash-breaking

#1437 update sei-cosmos dependency to v0.2.77
  go.mod
  go.sum
Labels: non-app-hash-breaking

#1438 Update sei cosmos 0.2.77 seiv2
  go.mod
  go.sum
Labels: non-app-hash-breaking

#1435 Transfer wei when account is associated
  x/evm/ante/preprocess.go
  x/evm/ante/preprocess_test.go
Labels: app-hash-breaking

#1443 Handle unprotected TXs properly
  x/evm/ante/preprocess.go
  x/evm/ante/preprocess_test.go
  x/evm/ante/sig.go
Labels: app-hash-breaking

#1426 Add utils to replay ETH mainnet txs
  app/app.go
  app/eth_replay.go
  cmd/seid/cmd/ethreplay.go
  cmd/seid/cmd/root.go
  x/evm/ante/preprocess.go
  x/evm/keeper/genesis.go
  x/evm/keeper/keeper.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/params.go
  x/evm/keeper/replay.go
  x/evm/keeper/state.go
  x/evm/module.go
  x/evm/replay/config.go
  x/evm/state/accesslist.go
  x/evm/state/balance.go
  x/evm/state/check.go
  x/evm/state/code.go
  x/evm/state/expected_keepers.go
  x/evm/state/nonce.go
  x/evm/state/state.go
  x/evm/types/keys.go
Labels: non-app-hash-breaking

#1447 Set association and account for EVM contracts
  precompiles/distribution/distribution_test.go
  precompiles/staking/staking.go
  precompiles/staking/staking_test.go
  x/evm/ante/preprocess.go
  x/evm/keeper/address.go
  x/evm/keeper/address_test.go
  x/evm/keeper/code.go
  x/evm/keeper/code_test.go
Labels: app-hash-breaking

#1448 Bump tendermint version to 0.2.40
  go.mod
  go.sum
Labels: non-app-hash-breaking

#1442 Associate Tx Prefix Fix
  evmrpc/association.go
  evmrpc/association_test.go
  go.mod
  go.sum
  proto/eth/tx.proto
  x/evm/ante/preprocess.go
  x/evm/ante/preprocess_test.go
  x/evm/types/ethtx/associate_tx.go
  x/evm/types/ethtx/tx.pb.go
Labels: app-hash-breaking

#1444 Adding tokenfactory denom metadata endpoint
  proto/README.md
  proto/tokenfactory/query.proto
  x/tokenfactory/keeper/grpc_query.go
  x/tokenfactory/keeper/grpc_query_test.go
  x/tokenfactory/types/query.pb.go
  x/tokenfactory/types/query.pb.gw.go
Labels: non-app-hash-breaking

#1440 Precompile Integration Tests
  contracts/package-lock.json
  contracts/package.json
  contracts/test/EVMPrecompileTester.js
  contracts/test/deploy_atom_erc20.sh
  contracts/test/get_validator_address.sh
  contracts/test/param_change_proposal.json
  contracts/test/send_gov_proposal.sh
  docker/localnode/Dockerfile
  docker/localnode/scripts/step1_configure_init.sh
  docker/localnode/scripts/step2_genesis.sh
  integration_test/evm_module/hardhat_test.yaml
  integration_test/gov_module/gov_proposal_test.yaml
  precompiles/addr/abi.json
  precompiles/bank/abi.json
  precompiles/common/erc20_abi.json
  precompiles/distribution/abi.json
  precompiles/gov/abi.json
  precompiles/staking/abi.json
  precompiles/wasmd/abi.json
  scripts/hardhat.sh
Labels: non-app-hash-breaking

#1453 [OCC] tick cosmos version to v0.2.78-seiv2
  go.mod
  go.sum
Labels: non-app-hash-breaking

#1454 Update openapi.yml
  docs/README.md
  docs/static/openapi.yml
Labels: documentation, non-app-hash-breaking

#1457 V3.8.2 release
  go.mod
  go.sum
Labels: non-app-hash-breaking

#1458 EVM Module Panic + Error Metrics
  x/evm/keeper/msg_server.go
Labels: non-app-hash-breaking

#1452 loadtest throughput metrics
  loadtest/loadtest_client.go
  loadtest/main.go
  loadtest/metrics.go
  loadtest/types.go
  utils/metrics/metrics_util.go
Labels: non-app-hash-breaking

#1449 Account for withdrawals in replay
  app/eth_replay.go
  x/evm/keeper/code.go
  x/evm/keeper/code_test.go
  x/evm/state/check.go
  x/evm/state/code_test.go
Labels: non-app-hash-breaking

#1461 Parallelize tx decoding/EVM preprocessing
  app/app.go
  app/app_test.go
Labels: non-app-hash-breaking

#1462 Remove redundant signature decoding
  x/evm/keeper/msg_server.go
Labels: non-app-hash-breaking

#1465 Set big int constants
  evmrpc/simulate.go
  evmrpc/subscribe.go
  precompiles/bank/bank.go
  utils/constants.go
  x/evm/ante/fee.go
  x/evm/ante/preprocess.go
  x/evm/client/cli/tx.go
  x/evm/keeper/evm.go
  x/evm/keeper/keeper.go
  x/evm/keeper/params.go
  x/evm/module.go
  x/evm/state/balance.go
  x/evm/state/check.go
  x/evm/state/statedb.go
  x/evm/state/utils.go
  x/evm/types/config.go
  x/evm/types/ethtx/legacy_tx.go
  x/evm/types/ethtx/txdata.go
Labels: non-app-hash-breaking

#1464 Update loadtest handlers to include parallel wasm message types
  loadtest/config.json
  loadtest/contracts/deploy_sei_tester.sh
  loadtest/contracts/sei_tester.wasm
  loadtest/loadtest_client.go
  loadtest/main.go
  loadtest/types.go
Labels: non-app-hash-breaking

#1468 Add occ metrics for gas used
  app/app.go
  utils/metrics/labels.go
Labels: non-app-hash-breaking

#1466 Add wasm binding for getting associated addresses
  wasmbinding/queries.go
  x/evm/client/wasm/bindings/queries.go
  x/evm/client/wasm/query.go
  x/evm/client/wasm/query_test.go
Labels: non-app-hash-breaking

#1455 EVM Blockchain tests
  app/app.go
  app/eth_replay.go
  cmd/seid/cmd/blocktest.go
  cmd/seid/cmd/root.go
  go.mod
  go.sum
  x/evm/blocktest/config.go
  x/evm/keeper/genesis.go
  x/evm/keeper/keeper.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/params.go
  x/evm/keeper/replay.go
  x/evm/module.go
Labels: non-app-hash-breaking

#1469 Not override log index
  evmrpc/filter.go
Labels: non-app-hash-breaking

#1445 Oracle Precompile
  app/app.go
  contracts/test/EVMPrecompileTester.js
  contracts/test/query_oracle_data.sh
  integration_test/evm_module/hardhat_test.yaml
  precompiles/common/expected_keepers.go
  precompiles/oracle/Oracle.sol
  precompiles/oracle/abi.json
  precompiles/oracle/oracle.go
  precompiles/oracle/oracle_test.go
  precompiles/setup.go
Labels: app-hash-breaking

#1481 [seiv2] fix golint
  cmd/seid/cmd/blocktest.go
  x/evm/module.go
Labels: non-app-hash-breaking

#1470 Add cosmos send to EVM addr transaction type
  go.mod
  go.sum
  proto/evm/tx.proto
  x/evm/client/cli/native_tx.go
  x/evm/client/cli/tx.go
  x/evm/handler.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/msg_server_test.go
  x/evm/types/codec.go
  x/evm/types/message_send.go
  x/evm/types/tx.pb.go
Labels: app-hash-breaking

#1471 cache block during eth replay
  app/eth_replay.go
  x/evm/keeper/keeper.go
Labels: non-app-hash-breaking

#1482 Add EVM panic stack trace
  x/evm/keeper/msg_server.go
Labels: non-app-hash-breaking

#1472 Ante Handler: Nested Evm Messages within Authz
  app/ante.go
  app/antedecorators/authz_nested_message.go
  app/antedecorators/authz_nested_message_test.go
Labels: app-hash-breaking

#1486 [EVM] Fix timestamp in evm read calls
  app/app.go
  contracts/src/EVMCompatibilityTester.sol
  contracts/test/EVMCompatabilityTester.js
  evmrpc/simulate.go
Labels: non-app-hash-breaking

#1485 IBC transfer precompile
  app/app.go
  precompiles/common/expected_keepers.go
  precompiles/common/precompiles.go
  precompiles/ibc/IBC.sol
  precompiles/ibc/abi.json
  precompiles/ibc/ibc.go
  precompiles/ibc/ibc_test.go
  precompiles/setup.go
  precompiles/wasmd/wasmd.go
  x/evm/keeper/genesis.go
  x/evm/keeper/keeper.go
Labels: app-hash-breaking

#1490 Add ERC pointer registry
  precompiles/common/expected_keepers.go
  precompiles/ibc/ibc.go
  precompiles/pointer/Pointer.sol
  precompiles/pointer/abi.json
  precompiles/pointer/pointer.go
  precompiles/pointer/pointer_test.go
  precompiles/pointerview/Pointerview.sol
  precompiles/pointerview/abi.json
  precompiles/pointerview/pointerview.go
  precompiles/pointerview/pointerview_test.go
  precompiles/setup.go
  precompiles/wasmd/wasmd.go
  utils/constants.go
  x/evm/artifacts/cw20/artifacts.go
  x/evm/artifacts/cw721/artifacts.go
  x/evm/artifacts/native/artifacts.go
  x/evm/client/cli/tx.go
  x/evm/keeper/pointer.go
  x/evm/keeper/pointer_test.go
  x/evm/types/keys.go
Labels: app-hash-breaking

#1375 Update that brings `go-ethereum` with live tracer support
  app/eth_replay.go
  evmrpc/simulate.go
  go.mod
  go.sum
  x/evm/module_test.go
  x/evm/state/balance.go
  x/evm/state/balance_test.go
  x/evm/state/check_test.go
  x/evm/state/code.go
  x/evm/state/log.go
  x/evm/state/nonce.go
  x/evm/state/state.go
  x/evm/state/state_test.go
  x/evm/state/statedb.go
Labels: non-app-hash-breaking
