Repository sei-protocol/sei-chain, pull requests merged in 2024-06, with the labels that each got.

#1660 Add light total supply invariance check
  app/app.go
  app/invariance.go
  app/invariance_test.go
  app/test_helpers.go
  cmd/seid/cmd/root.go
Labels: non-app-hash-breaking

#1698 Allow eip1559 txs in loadtest
  loadtest/config.json
  loadtest/evm.go
  loadtest/loadtest_client.go
  loadtest/types.go
Labels: non-app-hash-breaking

#1697 EVM gas price metrics
  go.mod
  go.sum
  utils/metrics/metrics_util.go
  x/evm/ante/fee.go
Labels: non-app-hash-breaking

#1670 Withdraw multiple delegation rewards
  precompiles/distribution/Distribution.sol
  precompiles/distribution/abi.json
  precompiles/distribution/distribution.go
  precompiles/distribution/distribution_test.go
Labels: app-hash-breaking

#1711 Add gov proposal v2 for native pointer
  contracts/test/CW20toERC20PointerTest.js
  contracts/test/ERC20toCW20PointerTest.js
  go.mod
  go.sum
  proto/evm/gov.proto
  x/evm/client/cli/gov_tx.go
  x/evm/client/cli/tx.go
  x/evm/gov.go
  x/evm/gov_test.go
  x/evm/handler.go
  x/evm/types/codec.go
  x/evm/types/gov.go
  x/evm/types/gov.pb.go
  x/evm/types/gov_test.go
Labels: app-hash-breaking

#1713 RPC Get Evm Hash
  contracts/test/EVMCompatabilityTest.js
  contracts/test/lib.js
  evmrpc/association.go
  evmrpc/association_test.go
  evmrpc/setup_test.go
Labels: non-app-hash-breaking

#1715 Fix for swagger docs serving
  app/app.go
  app/app_test.go
  config.yml
  docs/README.md
  docs/docs.go
  docs/static/openapi.yml
  docs/swagger-ui/favicon-16x16.png
  docs/swagger-ui/favicon-32x32.png
  docs/swagger-ui/index.css
  docs/swagger-ui/index.html
  docs/swagger-ui/oauth2-redirect.html
  docs/swagger-ui/swagger-initializer.js
  docs/swagger-ui/swagger-ui-bundle.js
  docs/swagger-ui/swagger-ui-bundle.js.map
  docs/swagger-ui/swagger-ui-es-bundle-core.js
  docs/swagger-ui/swagger-ui-es-bundle-core.js.map
  docs/swagger-ui/swagger-ui-es-bundle.js
  docs/swagger-ui/swagger-ui-es-bundle.js.map
  docs/swagger-ui/swagger-ui-standalone-preset.js
  docs/swagger-ui/swagger-ui-standalone-preset.js.map
  docs/swagger-ui/swagger-ui.css
  docs/swagger-ui/swagger-ui.css.map
  docs/swagger-ui/swagger-ui.js
  docs/swagger-ui/swagger-ui.js.map
  docs/swagger-ui/swagger.yml
  docs/swagger/init.go
  scripts/update-swagger-ui-statik.sh
Labels: documentation, non-app-hash-breaking

#1721 Bump ibc
  go.mod
  go.sum
Labels: app-hash-breaking

#1714 Bump geth to v1.13.5-sei-21
  go.mod
  go.sum
Labels: app-hash-breaking

#1717 Register evm (and other missing) module grpc routes endpoints
  x/epoch/module.go
  x/epoch/module_test.go
  x/evm/module.go
  x/evm/module_test.go
Labels: non-app-hash-breaking

#1718 Allow bank precompile to use the unassociated casted address for receiving balances
  contracts/test/ERC20toNativePointerTest.js
  contracts/test/lib.js
  precompiles/bank/bank.go
  precompiles/bank/bank_test.go
Labels: app-hash-breaking

#1726 Handle VM error code properly
  x/evm/keeper/keeper.go
Labels: app-hash-breaking

#1722 Bump Sei Cosmos
  go.mod
  go.sum
  precompiles/bank/bank_test.go
  x/evm/keeper/keeper.go
  x/evm/keeper/msg_server_test.go
Labels: non-app-hash-breaking

#1725 Add v5.5.5 upgrade
  CHANGELOG.md
  app/upgrades.go
Labels: app-hash-breaking

#1719 Fixes local network in /scripts/run-node.py
  scripts/run-node.py
Labels: non-app-hash-breaking

#1728 Make occ caused evm panics less noisy
  x/evm/keeper/msg_server.go
Labels: non-app-hash-breaking

#1727 [EVM] Add association error metric
  evmrpc/simulate.go
  evmrpc/utils.go
  precompiles/addr/addr.go
  precompiles/common/precompiles.go
  precompiles/common/precompiles_test.go
  precompiles/distribution/distribution.go
  precompiles/distribution/distribution_test.go
  precompiles/gov/gov.go
  precompiles/gov/gov_test.go
  precompiles/ibc/ibc.go
  precompiles/staking/staking.go
  precompiles/wasmd/wasmd.go
  utils/metrics/metrics_util.go
  wasmbinding/queries.go
  x/evm/ante/preprocess.go
  x/evm/client/wasm/bindings/queries.go
  x/evm/client/wasm/query.go
  x/evm/keeper/evm.go
  x/evm/keeper/evm_test.go
  x/evm/types/errors.go
  x/evm/types/errors_test.go
Labels: non-app-hash-breaking

#1729 Remove interoperability hop limit with isolated EVM instances
  contracts/test/CW20toERC20PointerTest.js
  contracts/test/lib.js
  evmrpc/tx.go
  go.mod
  go.sum
  precompiles/wasmd/wasmd.go
  precompiles/wasmd/wasmd_test.go
  x/evm/client/cli/common.go
  x/evm/keeper/evm.go
  x/evm/keeper/evm_test.go
Labels: app-hash-breaking

#1732 Show empty trace on insufficient funds error
  go.mod
  go.sum
Labels: non-app-hash-breaking

#1733 Update getBlockReceipts to accept block hash
  evmrpc/block.go
  evmrpc/block_test.go
  evmrpc/setup_test.go
Labels: non-app-hash-breaking

#1738 Reduce Default TTL configs
  app/params/config.go
  docs/migration/seiv2_config_migration.md
Labels: non-app-hash-breaking

#1736 Create account for sendNative receiver
  app/app.go
  precompiles/bank/bank.go
  precompiles/bank/bank_test.go
  precompiles/common/expected_keepers.go
  precompiles/setup.go
Labels: app-hash-breaking

#1734 Add migration to unwind dex state
  .github/workflows/integration-test.yml
  aclmapping/dex/mappings_test.go
  app/app.go
  app/upgrades.go
  tests/dex_test.go
  x/dex/keeper/keeper.go
  x/dex/keeper/msgserver/msg_server_cancel_orders.go
  x/dex/keeper/msgserver/msg_server_cancel_orders_test.go
  x/dex/keeper/msgserver/msg_server_contract_deposit_rent.go
  x/dex/keeper/msgserver/msg_server_contract_deposit_rent_test.go
  x/dex/keeper/msgserver/msg_server_place_orders.go
  x/dex/keeper/msgserver/msg_server_place_orders_test.go
  x/dex/keeper/msgserver/msg_server_register_contract.go
  x/dex/keeper/msgserver/msg_server_register_contract_test.go
  x/dex/keeper/msgserver/msg_server_register_pairs.go
  x/dex/keeper/msgserver/msg_server_register_pairs_test.go
  x/dex/keeper/msgserver/msg_server_test.go
  x/dex/keeper/msgserver/msg_server_unregister_contract.go
  x/dex/keeper/msgserver/msg_server_unregister_contract_test.go
  x/dex/keeper/msgserver/msg_server_unsuspend_contract.go
  x/dex/keeper/msgserver/msg_server_unsuspend_contract_test.go
  x/dex/keeper/msgserver/msg_server_update_price_tick_size.go
  x/dex/keeper/msgserver/msg_server_update_price_tick_size_test.go
  x/dex/keeper/msgserver/msg_server_update_quantity_tick_size.go
  x/dex/keeper/msgserver/msg_server_update_quantity_tick_size_test.go
  x/dex/migrations/v17_to_v18.go
  x/dex/migrations/v17_to_v18_test.go
  x/dex/module.go
Labels: app-hash-breaking

#1740 Update Random to Hash of Block Timestamp
  x/evm/keeper/keeper.go
Labels: app-hash-breaking

#1737 Only send unlocked tokens upon address association
  x/evm/ante/preprocess.go
  x/evm/ante/preprocess_test.go
Labels: app-hash-breaking

#1743 bump tendermint
  go.mod
  go.sum
Labels: non-app-hash-breaking

#1746 Revert "Remove interoperability hop limit with isolated EVM instances (#1729)"
  contracts/test/CW20toERC20PointerTest.js
  contracts/test/lib.js
  evmrpc/tx.go
  precompiles/wasmd/wasmd.go
  precompiles/wasmd/wasmd_test.go
  x/evm/client/cli/common.go
  x/evm/keeper/evm.go
  x/evm/keeper/evm_test.go
Labels: app-hash-breaking

#1742 [EVM] Add transient receipts with eventual flush to store
  app/app.go
  app/test_helpers.go
  app/test_state_store.go
  app/test_state_store_test.go
  cmd/seid/cmd/blocktest.go
  cmd/seid/cmd/ethreplay.go
  cmd/seid/cmd/root.go
  docker/localnode/Dockerfile
  evmrpc/filter_test.go
  evmrpc/setup_test.go
  evmrpc/tx_test.go
  go.mod
  go.sum
  testutil/network/network.go
  x/evm/artifacts/native/artifacts_test.go
  x/evm/client/wasm/query_test.go
  x/evm/genesis_test.go
  x/evm/integration_test.go
  x/evm/keeper/keeper.go
  x/evm/keeper/msg_server.go
  x/evm/keeper/msg_server_test.go
  x/evm/keeper/receipt.go
  x/evm/keeper/receipt_test.go
  x/evm/module.go
  x/evm/module_test.go
  x/evm/types/keys.go
Labels: app-hash-breaking

#1690 Use transient store for EVM deferred info
  app/ante.go
  app/ante_test.go
  app/app.go
  go.mod
  go.sum
  proto/evm/types.proto
  x/evm/ante/error.go
  x/evm/ante/error_test.go
  x/evm/keeper/ante.go
  x/evm/keeper/deferred.go
  x/evm/keeper/keeper.go
  x/evm/keeper/keeper_test.go
  x/evm/keeper/msg_server.go
  x/evm/module.go
  x/evm/module_test.go
  x/evm/types/keys.go
  x/evm/types/message_evm_transaction.go
  x/evm/types/types.pb.go
Labels: non-app-hash-breaking

#1751 Update dependencies and changelog for v5.6.0 upgrade
  CHANGELOG.md
  go.mod
  go.sum
Labels: app-hash-breaking

#1752 Add sorting to a test store to fix flaky test
  app/test_state_store.go
Labels: non-app-hash-breaking

#1749 Update Readme
  readme.md
Labels: non-app-hash-breaking
